# tensorflow #

- outline
  - Eager Api
  - 基楚運算元（operations)

##  Eager Api ##

`eager execution` 是一個立即執行、difine by run 的interface。在python呼叫之後，運算即立刻開始。是學習tensorflow很好的入門方式。也可以讓研究開發過程更佳的直覺。大步份的`tf` api不論eager execution是否啟用，動作都相同。因此，相同的tf code建構出的 `tensorflow graph`（使用`layers api`）可以使用 eager execution執行；相對的，大部份啟用eager execution寫的model可以直接被轉譯`graph`來做進一步的優化動作，使其商品化。
https://research.googleblog.com/2017/10/eager-execution-imperative-define-by.html

In [1]:
from __future__ import absolute_import, division, print_function

import numpy as np
import tensorflow as tf

In [2]:
# set eager API
print("setting eager mode...")
tf.enable_eager_execution()
tfe = tf.contrib.eager

setting eager mode...


In [3]:
# define constant tensors
print("define costant tensors...")
a = tf.constant(2)
print("a = %i" % a)
b = tf.constant(3)
print("b = %i" % b)

define costant tensors...
a = 2
b = 3


In [4]:
# Run the operation without the need for tf.Session
print("Running operations, without tf.Session")
c = a + b
print("a + b = %i" % c)
d = a * b
print("a * b = %i" % d)

Running operations, without tf.Session
a + b = 5
a * b = 6


In [5]:
# Full compatibility with Numpy
print("Mixing operations with Tensors and Numpy Arrays")

# Define constant tensors
a = tf.constant([[2., 1.],
                 [1., 0.]], dtype=tf.float32)
print("Tensor:\n a = %s" % a)
b = np.array([[3., 0.],
              [5., 1.]], dtype=np.float32)
print("NumpyArray:\n b = %s" % b)

Mixing operations with Tensors and Numpy Arrays
Tensor:
 a = tf.Tensor(
[[ 2.  1.]
 [ 1.  0.]], shape=(2, 2), dtype=float32)
NumpyArray:
 b = [[ 3.  0.]
 [ 5.  1.]]


In [6]:
# Run the operation without the need for tf.Session
print("Running operations, without tf.Session")

c = a + b
print("a + b = %s" % c)

d = tf.matmul(a, b)
print("a * b = %s" % d)

Running operations, without tf.Session
a + b = tf.Tensor(
[[ 5.  1.]
 [ 6.  1.]], shape=(2, 2), dtype=float32)
a * b = tf.Tensor(
[[ 11.   1.]
 [  3.   0.]], shape=(2, 2), dtype=float32)


In [7]:
print("Iterate through Tensor 'a':")
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        print(a[i][j])

Iterate through Tensor 'a':
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)


### 基礎運算元（operations) ###

* 基礎常數運算元  
回傳值為其ouput
* 矩陣運算  
tf 支援矩陣運算，並且與 `numpy`相容。
```4^5^

In [ ]:
from IPython.core.display import HTML
HTML("<script>Jupyter.notebook.kernel.restart()</script>")

In [2]:
from __future__ import absolute_import, division, print_function

import numpy as np
import tensorflow as tf
a = tf.constant(2)
b = tf.constant(3)

with tf.Session() as sess:
    print("a: %i" % sess.run(a),  "b: %i" % sess.run(b))
    print("additon with constants: %i" % sess.run(a+b))
    print("multiplication with the constants: %i" % sess.run(a*b))

a: 2 b: 3
additon with constants: 5
multiplication with the constants: 6
